/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';
import { useSpring, a } from '@react-spring/three';
import { useFrame } from '@react-three/fiber';

export default function Cup(props) {
  const scaleSize = 0.1;
  const mugProps = useSpring({ scale: [scaleSize, scaleSize, scaleSize] });
  const group = useRef();
  // useFrame(() => {
  //   group.current.rotation.z = group.current.rotation.z += 0.01;
  // });
  const { nodes, materials } = useGLTF('/CUP.gltf');
  return (
    <group ref={group} {...props} dispose={null}>
      <a.mesh
        geometry={nodes.CUP.geometry}
        material={materials.DefaultMaterial}
        position={[-0.18, 0, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={mugProps.scale}
        castShadow
      />
    </group>
  );
}

useGLTF.preload('/CUP.gltf');
