/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';
import { useSpring, a } from '@react-spring/three';
import { useFrame } from '@react-three/fiber';

export default function Mug(props) {
  const scaleSize = 0.3;
  const group = useRef();
  // useFrame(() => {
  //   group.current.rotation.z = group.current.rotation.z += 0.01;
  // });
  const { nodes, materials } = useGLTF('/mug.gltf');
  const mugProps = useSpring({ scale: [scaleSize, scaleSize, scaleSize] });
  return (
    <group ref={group} {...props} dispose={null}>
      <a.mesh
        geometry={nodes.Node.geometry}
        material={materials.wire_153228184}
        castShadow
        scale={mugProps.scale}
      />
    </group>
  );
}

useGLTF.preload('/mug.gltf');
